version: '3.8'

services:
  central-server:
    build:
      context: .
      dockerfile: DockerfileCentral
    container_name: central-server
    ports:
      - "9092:9091"
    environment:
      - EMPLOYEE_NAMES=alice-white,bob-smith,carol-simpson,david-black,eva-brown
    volumes:
      - ./server-output:/app/server-output

  alice-white:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: alice-white
    ports:
      - "8081:8081"
    environment:
      - EMPLOYEE_USERNAME=alice-white
      - EMPLOYEE_NAME=Alice White
    depends_on:
      - central-server
    volumes:
      - ./employee-output:/app/employee-output

  bob-smith:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: bob-smith
    ports:
      - "8082:8081"
    environment:
      - EMPLOYEE_USERNAME=bob-smith
      - EMPLOYEE_NAME=Bob Smith
    depends_on:
      - central-server
    volumes:
      - ./employee-output:/app/employee-output

  carol-simpson:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: carol-simpson
    ports:
      - "8083:8081"
    environment:
      - EMPLOYEE_USERNAME=carol-simpson
      - EMPLOYEE_NAME=Carol Simpson
    depends_on:
      - central-server
    volumes:
      - ./employee-output:/app/employee-output

  david-black:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: david-black
    ports:
      - "8084:8081"
    environment:
      - EMPLOYEE_USERNAME=david-black
      - EMPLOYEE_NAME=David Black
    depends_on:
      - central-server
    volumes:
      - ./employee-output:/app/employee-output

  eva-brown:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: eva-brown
    ports:
      - "8085:8081"
    environment:
      - EMPLOYEE_USERNAME=eva-brown
      - EMPLOYEE_NAME=Eva Brown
    depends_on:
      - central-server
    volumes:
      - ./employee-output:/app/employee-output