version: '3.8'

services:
  central-server:
    build:
      context: .
      dockerfile: DockerfileCentral
    container_name: central-server
    ports:
      - "9092:9091"
    environment:
      - EMPLOYEE_NAMES=alice-white,bob-smith,carol-simpson,david-black,eva-brown
    volumes:
      - ./server-output:/app/server-output

  alice-white:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: alice-white
    ports:
      - "8081:8081"
    depends_on:
      - central-serverY

  bob-smith:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: bob-smith
    ports:
      - "8082:8081"
    depends_on:
      - central-server

  carol-simpson:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: carol-simpson
    ports:
      - "8083:8081"
    depends_on:
      - central-server

  david-black:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: david-black
    ports:
      - "8084:8081"
    depends_on:
      - central-server

  eva-brown:
    build:
      context: .
      dockerfile: DockerfileEmployee
    container_name: eva-brown
    ports:
      - "8085:8081"
    depends_on:
      - central-server